### ISSUE TITLE
训练时，steps_check的时候打印出来的loss固定不下降

### ISSUE THREAD

**Issue by tangyaohua** [xxxsssyyy/SimCSE-tensorflow#2]

**Comment by tangyaohua** [comment]
一直是一个值，每个batch的loss也是同样的一个值

**Comment by xxxsssyyy** [comment]
你用的是什么数据呢，我这里没出现过这样的情况

**Comment by tangyaohua** [comment]
可否上传一下您的bert目录，我对比下我的

**Comment by tangyaohua** [comment]
换成atec的数据集依然一样，打印出来的梯度都是0，所以看看是不是bert目录跟您不同

**Comment by xxxsssyyy** [comment]
> 可否上传一下您的bert目录，我对比下我的
看一下下面中的bert目录
https://github.com/xxxsssyyy/DeepNER

**Comment by tangyaohua** [comment]
多谢，找到问题原因了

**Comment by xxxsssyyy** [comment]
> 多谢，找到问题原因了

是什么问题呢
